In [ ]:
%pip install numpy

In [22]:
import numpy as np 

1) Create a NumPy array: Create a 1D NumPy array with the numbers 1 through 10.

In [29]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6,7,8,9,10]) ## version 1
print(arr1)
arr2 = np.arange(1,11) # version 2
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


2) Array indexing: Access the 5th element of a NumPy array containing the numbers 1 through 10.

In [30]:
import numpy as np 
arr3 = np.arange(1,11)
print(arr3[5])


6


3) Array slicing: Create a NumPy array with the numbers 1 through 10 and slice it to get the first 5 elements.

In [31]:
import numpy as np 
arr4 = np.arange(1,11)
print(arr4[:5])


[1 2 3 4 5]


4) Basic arithmetic: Perform element-wise addition, subtraction, multiplication, and division on two 1D arrays.

In [34]:
import numpy as np 

arr51=np.array([1,2,3,6])
arr52=np.array([1,2,3,6])
arr53=np.array([1,1,1,1])
arr54=np.array([1,1,1,0])

print(arr51+arr52)
print(arr51-arr52)
print(arr51*arr52)
print(arr51//arr53)


print(arr51//arr54) ## Runtime warning 


[ 2  4  6 12]
[0 0 0 0]
[ 1  4  9 36]
[1 2 3 6]
[1 2 3 0]


/var/folders/_s/g54k_qps0dl4jnczql8p3x940000gn/T/ipykernel_1416/139172400.py:14: RuntimeWarning: divide by zero encountered in floor_divide
  print(arr51//arr54)


5) Reshape array: Create a 1D array of 9 elements and reshape it into a 3x3 matrix.

In [38]:
import numpy as np 
arr6 = np.arange(9)
print(arr6.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6) Array statistics: Find the mean, median, and standard deviation of a NumPy array of random numbers.

In [104]:
import numpy as np 
arr7 = np.random.randint(1,10,(1,10))
meaned= np.mean(arr7)
medianed= np.median(arr7)
stdvar=np.std(arr7)
print(arr7)
print(meaned) ## mijin
print(medianed)  ## mechtexi tiv ete achman kargov enq sharum 
print(stdvar) ## mijin hanac amen mi andmay u armati tak 

[[9 8 7 9 2 8 4 3 3 8]]
6.1
7.5
2.6248809496813377


7) Broadcasting: Add a 1D array [1, 2, 3] to a 3x3 matrix.

In [138]:
import numpy as np 
matrix1 =np.random.randint(1,10, (3,3))
arrr= np.array([1,2,3])
print(matrix1, )
print(matrix1+arrr)

[[8 2 5]
 [6 9 6]
 [9 1 2]]
[[ 9  4  8]
 [ 7 11  9]
 [10  3  5]]


8) Matrix multiplication: Multiply two 2D arrays (matrices) together using NumPy.

In [167]:
import numpy as np 
mtrx1=np.random.randint(1,10,(3,3))
mtrx2=np.random.randint(1,10,(3,3))
print(mtrx1.dot(mtrx2))

[[100  55 100]
 [115 101 133]
 [ 58  55  90]]


9) Array stacking: Stack two 1D arrays vertically and horizontally

In [217]:
import numpy as np 
starr1= numpy.random.randint(1,5,(2,2)) ## there my arrays aren't 1D
starr2= numpy.random.randint(1,5,(2,2))

sth= np.hstack((starr1, starr2))
print(sth)

stv= np.vstack((starr1, starr2))
print(stv)


[[1 3 1 3]
 [2 3 2 3]]
[[1 3]
 [2 3]
 [1 3]
 [2 3]]


+ 10) Element-wise operations: Apply a function (e.g., np.sin(), np.exp()) element-wise to a NumPy array.

In [199]:
import numpy as np 
arr128=np.array([0,1,2,3,4])
print(np.sin(arr128))
print(np.exp(arr128))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


+ 11) Array of zeros with specific data type: Create a 4x4 matrix of zeros with a data type of float64 using np.zeros().

In [234]:
import numpy as np
zer= np.zeros((4,4), dtype='float64')
zer

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

+ 12) Matrix manipulation: Create a 5x5 matrix of zeros and set the diagonal elements to ones.

In [228]:
import numpy as np
diag = np.eye(5, dtype="int")
diag

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

+ 13) Unique elements: Find the unique elements of a NumPy array and count their occurrences.

In [589]:
import numpy as np
ar13=np.random.randint(1, 10, (10,1))
counts=np.unique_counts(ar13)

print(counts.values, "Oringinal List")
print(counts.counts, "Their occurecies")


[1 2 3 5 6 7 9] Oringinal List
[1 1 1 2 2 2 1] Their occorecies


+ 14) Random numbers: Generate an array of 10 random integers between 1 and 100.

In [601]:
import numpy as np
ar14= np.random.randint(1,100,(10,))
ar14

array([ 9, 72, 53, 91, 74, 65, 42, 68, 34, 41])

+ 15) Array comparison: Compare two NumPy arrays and return an array of boolean values where the elements are equal.

In [640]:
import numpy as np
ar15_1=np.random.randint(1,5,(10,))
ar15_2=np.random.randint(1,5,(10,))
print((ar15_1== ar15_2))

[False False False False False  True False False False False]


+ 16) Sorting and searching: Sort a NumPy array and find the index of the maximum element.

In [649]:
import numpy as np
ar16= np.random.randint(1,100,(10,))
print(numpy.sort(ar16))
print(numpy.sort(ar16)[-1])

[ 6 10 12 20 30 42 50 63 82 92]
92


+ 17)  Install PyTorch and Verify Setup:Install PyTorch on your system and verify the installation by running a simple code to check the version and ensure it's working.

In [220]:
%pip install torch

  Using cached setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 MB 284.6 kB/s eta 0:00:0000:0100:08
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 551.5 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 335.8 kB/s eta 0:00:00a 0:00:01
Using cached setuptools-75.8.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 434.7 kB/s eta 0:00:0000:01m

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [225]:
%pip show torch

Name: torch
Version: 2.6.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages
Requires: filelock, fsspec, jinja2, networkx, setuptools, sympy, typing-extensions
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [651]:
import torch 
t= torch.eye(3)
t

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

+ 18) Tensors Basics:Create a 2D tensor of shape (3, 3) filled with zeros. Then, create a tensor filled with ones and add both tensors together.

In [658]:
import torch
t_18=torch.zeros(3,3)
o_18=torch.ones(3,3)
print(t_18+o_18)
print(torch.hstack((t_18,o_18)))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])


+ 19) Tensor Operations: Create two tensors, A and B, of size (3, 3). Perform element-wise addition, subtraction, multiplication, and division on them.

In [664]:
import torch
A=torch.randint(1,9,(3,3))
B=torch.randint(1,9,(3,3))

print(A+B)
print(A-B)
print(A*B)
print(A//B)

tensor([[ 5, 11, 12],
        [ 8, 13,  7],
        [ 5,  6, 12]])
tensor([[ 3, -1, -4],
        [ 0, -3, -1],
        [-3, -2,  4]])
tensor([[ 4, 30, 32],
        [16, 40, 12],
        [ 4,  8, 32]])
tensor([[4, 0, 0],
        [1, 0, 0],
        [0, 0, 2]])


+ 20) Tensor Indexing and Slicing: Create a tensor of shape (4, 4). Slice the tensor to extract a sub-tensor of shape (2, 2) from the bottom-right corner

In [666]:
import torch

A=torch.randint(1,9,(4,4))
print(A)
print(A[2:,2:])

tensor([[6, 3, 4, 4],
        [5, 6, 7, 3],
        [4, 1, 1, 8],
        [7, 1, 8, 8]])
tensor([[1, 8],
        [8, 8]])


+ 21) Reshaping Tensors: Create a tensor of shape (8, 4). Reshape it into a tensor of shape (4, 8) and verify the new shape.

In [672]:
import torch

A=torch.randint(1,9,(4,8))
print(A)
print(A.reshape(8,4))

tensor([[1, 2, 4, 3, 5, 4, 1, 7],
        [5, 3, 8, 8, 4, 7, 8, 1],
        [3, 1, 4, 3, 4, 6, 7, 8],
        [3, 8, 3, 4, 3, 2, 5, 6]])
tensor([[1, 2, 4, 3],
        [5, 4, 1, 7],
        [5, 3, 8, 8],
        [4, 7, 8, 1],
        [3, 1, 4, 3],
        [4, 6, 7, 8],
        [3, 8, 3, 4],
        [3, 2, 5, 6]])


22) Matrix Multiplication: Create two tensors A and B with shapes (3, 2) and (2, 3), respectively. Perform matrix multiplication using PyTorch’s mm() function. 

In [685]:
import torch

A=torch.randint(1,9,(3,2))
B=torch.randint(1,9,(2,3))
print(A)
print(B)
mult = torch.mm(A, B)
print(mult)

tensor([[8, 4],
        [6, 2],
        [8, 5]])
tensor([[5, 6, 6],
        [1, 1, 7]])
tensor([[44, 52, 76],
        [32, 38, 50],
        [45, 53, 83]])
